import React from "react";
import { jsPDF } from "jspdf";
import { FileDown } from "lucide-react";
import "../CSS/GameInstructionPDF.css";

export default function GameInstructionPDF({ game }) {
  const generatePDF = () => {
    const doc = new jsPDF();

    // ===== 🎯 HEADER =====
    doc.setFillColor(255, 255, 255); // white background
    doc.rect(0, 0, 210, 297, "F");

    // Title and Logo
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text("🎮 PlayfulOutings Game Instructions", 20, 20);

    doc.setDrawColor(100, 100, 100);
    doc.line(20, 24, 190, 24); // underline

    // ===== 🏷 GAME DETAILS =====
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`${game.name}`, 20, 38);

    doc.setFontSize(12);
    doc.text(`Category: ${game.category || "Not specified"}`, 20, 48);
    doc.text(`Duration: ${game.duration}`, 20, 56);
    doc.text(`Popularity: ${game.popularity} / 5`, 20, 64);

    // ===== 📜 DESCRIPTION =====
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text("Description:", 20, 78);
    const wrappedDescription = doc.splitTextToSize(game.description, 170);
    doc.text(wrappedDescription, 25, 85);

    // ===== 📍 LOCATIONS =====
    let yPos = 110;
    doc.setFontSize(13);
    doc.setTextColor(0, 0, 0);
    doc.text("Available Locations:", 20, yPos);

    yPos += 8;
    game.locations.forEach((loc, i) => {
      const priceText = loc.ticketPrice ? `₦${loc.ticketPrice}` : "Free Entry";
      doc.text(`${i + 1}. ${loc.name} — ${priceText}`, 25, yPos);
      yPos += 7;
    });

    // ===== 💡 EXTRA TIPS =====
    if (game.tips) {
      yPos += 10;
      doc.setTextColor(0, 102, 204);
      doc.text("Tips & Recommendations:", 20, yPos);
      doc.setTextColor(60, 60, 60);
      const wrappedTips = doc.splitTextToSize(game.tips, 170);
      doc.text(wrappedTips, 25, yPos + 7);
    }

    // ===== 📅 FOOTER =====
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by PlayfulOutings — Explore, Play, and Enjoy!", 20, 285);
    doc.text("© 2025 PlayfulOutings. All Rights Reserved.", 20, 292);

    // ===== 💾 SAVE PDF =====
    doc.save(`${game.name}_Instructions.pdf`);
  };

  return (
    <button className="download-btn" onClick={generatePDF}>
      <FileDown size={16} />
      Download Game Instructions
    </button>
  );
}
